/* tslint:disable */
/* eslint-disable */
/**
 * Flight Ticket API
 * API documentation for the Flight Ticket backend.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FlightTicket,
} from '../models/index';
import {
    FlightTicketFromJSON,
    FlightTicketToJSON,
} from '../models/index';

export interface CreateTicketRequest {
    flightTicket: FlightTicket;
}

export interface DeleteTicketRequest {
    id: number;
}

export interface GetTicketByIdRequest {
    id: number;
}

export interface SearchTicketsRequest {
    bookingDate?: Date;
    destination?: string;
    kickoff?: Date;
    name?: string;
    pickupAddress?: string;
    price?: number;
    sort?: string;
}

/**
 * 
 */
export class FlightTicketControllerApi extends runtime.BaseAPI {

    /**
     */
    async createTicketRaw(requestParameters: CreateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['flightTicket'] == null) {
            throw new runtime.RequiredError(
                'flightTicket',
                'Required parameter "flightTicket" was null or undefined when calling createTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/tickets`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FlightTicketToJSON(requestParameters['flightTicket']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async createTicket(requestParameters: CreateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.createTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteTicketRaw(requestParameters: DeleteTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/tickets/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteTicket(requestParameters: DeleteTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTicketRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getAllTicketsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FlightTicket>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/tickets`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FlightTicketFromJSON));
    }

    /**
     */
    async getAllTickets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FlightTicket>> {
        const response = await this.getAllTicketsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getTicketByIdRaw(requestParameters: GetTicketByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FlightTicket>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTicketById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/tickets/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FlightTicketFromJSON(jsonValue));
    }

    /**
     */
    async getTicketById(requestParameters: GetTicketByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FlightTicket> {
        const response = await this.getTicketByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async searchTicketsRaw(requestParameters: SearchTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FlightTicket>>> {
        const queryParameters: any = {};

        if (requestParameters['bookingDate'] != null) {
            queryParameters['bookingDate'] = (requestParameters['bookingDate'] as any).toISOString();
        }

        if (requestParameters['destination'] != null) {
            queryParameters['destination'] = requestParameters['destination'];
        }

        if (requestParameters['kickoff'] != null) {
            queryParameters['kickoff'] = (requestParameters['kickoff'] as any).toISOString();
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['pickupAddress'] != null) {
            queryParameters['pickupAddress'] = requestParameters['pickupAddress'];
        }

        if (requestParameters['price'] != null) {
            queryParameters['price'] = requestParameters['price'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/tickets/search`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FlightTicketFromJSON));
    }

    /**
     */
    async searchTickets(requestParameters: SearchTicketsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FlightTicket>> {
        const response = await this.searchTicketsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
