/* tslint:disable */
/* eslint-disable */
/**
 * Flight Ticket API
 * API documentation for the Flight Ticket backend.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RoutePricing,
} from '../models/index';
import {
    RoutePricingFromJSON,
    RoutePricingToJSON,
} from '../models/index';

export interface AddPriceRequest {
    routePricing: RoutePricing;
}

export interface SearchPriceRequest {
    kickoffAddress: string;
    destination: string;
}

/**
 * 
 */
export class RoutePricingControllerApi extends runtime.BaseAPI {

    /**
     */
    async addPriceRaw(requestParameters: AddPriceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['routePricing'] == null) {
            throw new runtime.RequiredError(
                'routePricing',
                'Required parameter "routePricing" was null or undefined when calling addPrice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/prices`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RoutePricingToJSON(requestParameters['routePricing']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async addPrice(requestParameters: AddPriceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.addPriceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAllPricesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RoutePricing>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/prices`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RoutePricingFromJSON));
    }

    /**
     */
    async getAllPrices(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RoutePricing>> {
        const response = await this.getAllPricesRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async searchPriceRaw(requestParameters: SearchPriceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['kickoffAddress'] == null) {
            throw new runtime.RequiredError(
                'kickoffAddress',
                'Required parameter "kickoffAddress" was null or undefined when calling searchPrice().'
            );
        }

        if (requestParameters['destination'] == null) {
            throw new runtime.RequiredError(
                'destination',
                'Required parameter "destination" was null or undefined when calling searchPrice().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['kickoffAddress'] != null) {
            queryParameters['kickoffAddress'] = requestParameters['kickoffAddress'];
        }

        if (requestParameters['destination'] != null) {
            queryParameters['destination'] = requestParameters['destination'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/prices/search`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async searchPrice(requestParameters: SearchPriceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.searchPriceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
