/* tslint:disable */
/* eslint-disable */
/**
 * Flight Ticket API
 * API documentation for the Flight Ticket backend.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FlightTicket
 */
export interface FlightTicket {
    /**
     * 
     * @type {number}
     * @memberof FlightTicket
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof FlightTicket
     */
    bookingDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof FlightTicket
     */
    destination?: string;
    /**
     * 
     * @type {Date}
     * @memberof FlightTicket
     */
    kickoff?: Date;
    /**
     * 
     * @type {string}
     * @memberof FlightTicket
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof FlightTicket
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof FlightTicket
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof FlightTicket
     */
    pickupAddress?: string;
    /**
     * 
     * @type {number}
     * @memberof FlightTicket
     */
    price?: number;
}

/**
 * Check if a given object implements the FlightTicket interface.
 */
export function instanceOfFlightTicket(value: object): value is FlightTicket {
    return true;
}

export function FlightTicketFromJSON(json: any): FlightTicket {
    return FlightTicketFromJSONTyped(json, false);
}

export function FlightTicketFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlightTicket {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'bookingDate': json['bookingDate'] == null ? undefined : (new Date(json['bookingDate'])),
        'destination': json['destination'] == null ? undefined : json['destination'],
        'kickoff': json['kickoff'] == null ? undefined : (new Date(json['kickoff'])),
        'name': json['name'] == null ? undefined : json['name'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'email': json['email'] == null ? undefined : json['email'],
        'pickupAddress': json['pickupAddress'] == null ? undefined : json['pickupAddress'],
        'price': json['price'] == null ? undefined : json['price'],
    };
}

export function FlightTicketToJSON(json: any): FlightTicket {
    return FlightTicketToJSONTyped(json, false);
}

export function FlightTicketToJSONTyped(value?: FlightTicket | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bookingDate': value['bookingDate'] == null ? undefined : ((value['bookingDate']).toISOString()),
        'destination': value['destination'],
        'kickoff': value['kickoff'] == null ? undefined : ((value['kickoff']).toISOString()),
        'name': value['name'],
        'phoneNumber': value['phoneNumber'],
        'email': value['email'],
        'pickupAddress': value['pickupAddress'],
        'price': value['price'],
    };
}

