/* tslint:disable */
/* eslint-disable */
/**
 * Flight Ticket API
 * API documentation for the Flight Ticket backend.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoutePricing
 */
export interface RoutePricing {
    /**
     * 
     * @type {number}
     * @memberof RoutePricing
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RoutePricing
     */
    kickoffAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof RoutePricing
     */
    destination?: string;
    /**
     * 
     * @type {number}
     * @memberof RoutePricing
     */
    normalPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof RoutePricing
     */
    vipPrice?: number;
}

/**
 * Check if a given object implements the RoutePricing interface.
 */
export function instanceOfRoutePricing(value: object): value is RoutePricing {
    return true;
}

export function RoutePricingFromJSON(json: any): RoutePricing {
    return RoutePricingFromJSONTyped(json, false);
}

export function RoutePricingFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoutePricing {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'kickoffAddress': json['kickoffAddress'] == null ? undefined : json['kickoffAddress'],
        'destination': json['destination'] == null ? undefined : json['destination'],
        'normalPrice': json['normalPrice'] == null ? undefined : json['normalPrice'],
        'vipPrice': json['vipPrice'] == null ? undefined : json['vipPrice'],
    };
}

export function RoutePricingToJSON(json: any): RoutePricing {
    return RoutePricingToJSONTyped(json, false);
}

export function RoutePricingToJSONTyped(value?: RoutePricing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'kickoffAddress': value['kickoffAddress'],
        'destination': value['destination'],
        'normalPrice': value['normalPrice'],
        'vipPrice': value['vipPrice'],
    };
}

